apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: ironclad-demo
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-provider
  namespace: ironclad-demo
data:
  dashboard.yaml: |
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        options:
          path: /etc/grafana/provisioning/dashboards

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: ironclad-demo
data:
  sre-overview.json: |
    {
      "dashboard": {
        "title": "Ironclad SRE Overview",
        "tags": ["sre", "overview"],
        "refresh": "30s",
        "panels": [
          {
            "id": 1,
            "title": "Service Health",
            "type": "stat",
            "gridPos": {"h": 4, "w": 6, "x": 0, "y": 0},
            "targets": [{"expr": "up{job=\"ironclad-backend\"}"}]
          },
          {
            "id": 2,
            "title": "Request Rate",
            "type": "timeseries",
            "gridPos": {"h": 8, "w": 12, "x": 0, "y": 4},
            "targets": [{"expr": "sum(rate(http_requests_total[5m])) by (method)"}]
          }
        ]
      }
    }
  infrastructure-metrics.json: |
    {
      "dashboard": {
        "title": "Infrastructure Metrics",
        "tags": ["infrastructure", "kubernetes"],
        "refresh": "30s",
        "panels": [
          {
            "id": 1,
            "title": "CPU Usage",
            "type": "timeseries",
            "gridPos": {"h": 8, "w": 12, "x": 0, "y": 0},
            "targets": [{"expr": "sum(rate(container_cpu_usage_seconds_total[5m])) by (pod)"}]
          }
        ]
      }
    }
  business-metrics.json: |
    {
      "dashboard": {
        "title": "Business Metrics",
        "tags": ["business", "kpi"],
        "refresh": "30s",
        "panels": [
          {
            "id": 1,
            "title": "Active Users",
            "type": "stat",
            "gridPos": {"h": 4, "w": 6, "x": 0, "y": 0},
            "targets": [{"expr": "active_users_current"}]
          }
        ]
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: ironclad-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: admin
        - name: GF_USERS_ALLOW_SIGN_UP
          value: "false"
        volumeMounts:
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: grafana-dashboard-provider
          mountPath: /etc/grafana/provisioning/dashboards
        - name: grafana-dashboards
          mountPath: /var/lib/grafana/dashboards
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: grafana-datasources
        configMap:
          name: grafana-datasources
      - name: grafana-dashboard-provider
        configMap:
          name: grafana-dashboard-provider
      - name: grafana-dashboards
        configMap:
          name: grafana-dashboards

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: ironclad-demo
spec:
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer