apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ironclad-backend:latest
        imagePullPolicy: Never
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_NAME
          value: ironclad_db
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: postgres
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer