groups:
  - name: ironclad_alerts
    interval: 30s
    rules:
      # High error rate
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
          team: sre
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} for {{ $labels.instance }}"

      # High latency
      - alert: HighLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 0.5
        for: 5m
        labels:
          severity: warning
          team: sre
        annotations:
          summary: "High latency detected"
          description: "95th percentile latency is {{ $value }}s"

      # Database connection issues
      - alert: DatabaseDown
        expr: up{job="ironclad-backend"} == 0
        for: 1m
        labels:
          severity: critical
          team: sre
        annotations:
          summary: "Database connection lost"
          description: "Cannot connect to database for {{ $labels.instance }}"

      # Error budget burn rate
      - alert: ErrorBudgetBurnRate
        expr: error_budget_remaining_percentage < 50
        for: 10m
        labels:
          severity: warning
          team: sre
        annotations:
          summary: "Error budget burning too fast"
          description: "Only {{ $value }}% of error budget remaining"