apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: ironclad-demo
type: Opaque
stringData:
  password: "IroncladSecurePass123!"
  
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: ironclad-demo
type: Opaque
stringData:
  db-password: "IroncladSecurePass123!"